In [22]:
import pandas as pd 
import numpy as np
import matplotlib

In [25]:
data = pd.read_csv('WtoData_Tableau.csv')

In [31]:
data = data.drop([0])

KeyError: '[0] not found in axis'

In [32]:
data

,Indicator,Merchandise exports by product group and destination â€“ annual (Million US dollar),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
1,Reporting Economy,Product/Sector,Partner Economy,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
2,World,SI3_AGG - AG - Agricultural products,World,568579.0,547798.0,549847.0,551329.0,583180.0,681678.0,781156.0,...,1177136.0,1354429.0,1649389.0,1655099.0,1731531.0,1752575.0,1561564.0,1579410.0,1734932.0,1806904.0
3,World,SI3_AGG - AGFO - Food,World,458577.0,438858.0,430043.0,442232.0,469058.0,549601.0,626602.0,...,998004.0,1115790.0,1350316.0,1369778.0,1445339.0,1479958.0,1329759.0,1351779.0,1474227.0,1532499.0
4,World,SI3_AGG - MA - Manufactures,World,4122548.0,4260117.0,4689533.0,4512734.0,4751628.0,5501386.0,6624576.0,...,8379712.0,9988931.0,11518898.0,11502948.0,11859117.0,12287237.0,11330715.0,11139789.0,12116430.0,13157224.0
5,World,SI3_AGG - MACH - Chemicals,World,519027.0,537217.0,584301.0,598611.0,666322.0,800741.0,975966.0,...,1453993.0,1694259.0,1984161.0,1960336.0,1997265.0,2048737.0,1844363.0,1816103.0,1984631.0,2237154.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6022,Zambia,SI3_AGG - MACH - Chemicals,World,NaN,9.0,4.0,10.0,9.0,9.0,41.0,...,87.0,138.0,232.0,258.0,646.0,392.0,186.0,209.0,372.0,367.0
6023,Zimbabwe,SI3_AGG - AG - Agricultural products,World,965.0,1141.0,1146.0,802.0,828.0,868.0,885.0,...,882.0,789.0,1171.0,1298.0,1252.0,1213.0,1176.0,1135.0,1050.0,1170.0
6024,Zimbabwe,SI3_AGG - AGFO - Food,World,NaN,957.0,906.0,684.0,582.0,699.0,586.0,...,403.0,585.0,843.0,1019.0,1083.0,1081.0,1085.0,1059.0,981.0,1040.0
6025,Zimbabwe,SI3_AGG - MA - Manufactures,World,NaN,508.0,539.0,180.0,716.0,433.0,532.0,...,765.0,1061.0,739.0,339.0,527.0,684.0,348.0,264.0,432.0,470.0
6026,Zimbabwe,SI3_AGG - MACH - Chemicals,World,NaN,50.0,53.0,9.0,95.0,55.0,28.0,...,22.0,22.0,27.0,21.0,33.0,21.0,22.0,14.0,14.0,17.0

In [35]:
data = data.transpose()

In [44]:
data.head(30)

,1,2,3,4,5,6,7,8,9,10,...,6017,6018,6019,6020,6021,6022,6023,6024,6025,6026
Indicator,Reporting Economy,World,World,World,World,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Africa,...,Yemen,Yemen,Zambia,Zambia,Zambia,Zambia,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe
Merchandise exports by product group and destination â€“ annual (Million US dollar),Product/Sector,SI3_AGG - AG - Agricultural products,SI3_AGG - AGFO - Food,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals,SI3_AGG - AG - Agricultural products,SI3_AGG - AGFO - Food,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals,SI3_AGG - AG - Agricultural products,...,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals,SI3_AGG - AG - Agricultural products,SI3_AGG - AGFO - Food,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals,SI3_AGG - AG - Agricultural products,SI3_AGG - AGFO - Food,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals
Unnamed: 2,Partner Economy,World,World,World,World,World,World,World,World,World,...,World,World,World,World,World,World,World,World,World,World
Unnamed: 3,1998,568579,458577,4.12255e+06,519027,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,965,NaN,NaN,NaN
Unnamed: 4,1999,547798,438858,4.26012e+06,537217,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,192,85,186,9,1141,957,508,50
Unnamed: 5,2000,549847,430043,4.68953e+06,584301,NaN,NaN,NaN,NaN,18212,...,NaN,NaN,92,68,184,4,1146,906,539,53
Unnamed: 6,2001,551329,442232,4.51273e+06,598611,NaN,NaN,NaN,NaN,18043,...,17,9,119,93,190,10,802,684,180,9
Unnamed: 7,2002,583180,469058,4.75163e+06,666322,NaN,NaN,NaN,NaN,19131,...,17,10,112,86,178,9,828,582,716,95
Unnamed: 8,2003,681678,549601,5.50139e+06,800741,NaN,NaN,NaN,NaN,23729,...,151,12,154,104,198,9,868,699,433,55
Unnamed: 9,2004,781156,626602,6.62458e+06,975966,NaN,NaN,NaN,NaN,27098,...,118,12,399,246,412,41,885,586,532,28
Unnamed: 10,2005,847715,680936,7.30272e+06,1.10175e+06,NaN,NaN,NaN,NaN,28559,...,150,16,340,239,320,15,454,357,451,27
Unnamed: 11,2006,942450,753836,8.26399e+06,1.24485e+06,NaN,NaN,NaN,NaN,30723,...,222,20,331,226,364,24,955,430,548,131
Unnamed: 12,2007,1.13169e+06,915653,9.5332e+06,1.47822e+06,NaN,NaN,NaN,NaN,34604,...,210,27,409,347,578,81,927,565,683,48
Unnamed: 13,2008,1.34282e+06,1.1147e+06,1.04758e+07,1.68418e+06,311,284,187,NaN,41542,...,444,33,341,285,635,72,598,285,731,58
Unnamed: 14,2009,1.17714e+06,998004,8.37971e+06,1.45399e+06,251,221,73,NaN,43113,...,254,38,384,324,437,87,882,403,765,22
Unnamed: 15,2010,1.35443e+06,1.11579e+06,9.98893e+06,1.69426e+06,197,156,76,NaN,48684,...,247,38,492,423,644,138,789,585,1061,22
Unnamed: 16,2011,1.64939e+06,1.35032e+06,1.15189e+07,1.98416e+06,196,147,53,NaN,57412,...,262,45,782,615,1089,232,1171,843,739,27
Unnamed: 17,2012,1.6551e+06,1.36978e+06,1.15029e+07,1.96034e+06,76,75,73,NaN,67991,...,262,46,1214,1029,1294,258,1298,1019,339,21
Unnamed: 18,2013,1.73153e+06,1.44534e+06,1.18591e+07,1.99726e+06,70,70,73,NaN,63495,...,180,39,1282,1080,1792,646,1252,1083,527,33
Unnamed: 19,2014,1.75258e+06,1.47996e+06,1.22872e+07,2.04874e+06,83,83,84,NaN,60376,...,544,41,850,704,1240,392,1213,1081,684,21
Unnamed: 20,2015,1.56156e+06,1.32976e+06,1.13307e+07,1.84436e+06,361,277,91,0,58399,...,190,15,701,613,767,186,1176,1085,348,22
Unnamed: 21,2016,1.57941e+06,1.35178e+06,1.11398e+07,1.8161e+06,437,339,39,NaN,59725,...,47,22,730,639,862,209,1135,1059,264,14
Unnamed: 22,2017,1.73493e+06,1.47423e+06,1.21164e+07,1.98463e+06,513,398,46,NaN,64366,...,62,22,649,585,1038,372,1050,981,432,14
Unnamed: 23,2018,1.8069e+06,1.5325e+06,1.31572e+07,2.23715e+06,576,447,52,NaN,NaN,...,82,14,635,551,1289,367,1170,1040,470,17

In [47]:
data[data['Mexico']]

KeyError: 'Mexico'

In [42]:
try_out

,1,2,3,4,5,6,7,8,9,10,...,6017,6018,6019,6020,6021,6022,6023,6024,6025,6026
Merchandise exports by product group and destination â€“ annual (Million US dollar),Product/Sector,SI3_AGG - AG - Agricultural products,SI3_AGG - AGFO - Food,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals,SI3_AGG - AG - Agricultural products,SI3_AGG - AGFO - Food,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals,SI3_AGG - AG - Agricultural products,...,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals,SI3_AGG - AG - Agricultural products,SI3_AGG - AGFO - Food,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals,SI3_AGG - AG - Agricultural products,SI3_AGG - AGFO - Food,SI3_AGG - MA - Manufactures,SI3_AGG - MACH - Chemicals
Unnamed: 2,Partner Economy,World,World,World,World,World,World,World,World,World,...,World,World,World,World,World,World,World,World,World,World
Unnamed: 3,1998,568579,458577,4.12255e+06,519027,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,965,NaN,NaN,NaN
Unnamed: 4,1999,547798,438858,4.26012e+06,537217,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,192,85,186,9,1141,957,508,50
Unnamed: 5,2000,549847,430043,4.68953e+06,584301,NaN,NaN,NaN,NaN,18212,...,NaN,NaN,92,68,184,4,1146,906,539,53
Unnamed: 6,2001,551329,442232,4.51273e+06,598611,NaN,NaN,NaN,NaN,18043,...,17,9,119,93,190,10,802,684,180,9
Unnamed: 7,2002,583180,469058,4.75163e+06,666322,NaN,NaN,NaN,NaN,19131,...,17,10,112,86,178,9,828,582,716,95
Unnamed: 8,2003,681678,549601,5.50139e+06,800741,NaN,NaN,NaN,NaN,23729,...,151,12,154,104,198,9,868,699,433,55
Unnamed: 9,2004,781156,626602,6.62458e+06,975966,NaN,NaN,NaN,NaN,27098,...,118,12,399,246,412,41,885,586,532,28
Unnamed: 10,2005,847715,680936,7.30272e+06,1.10175e+06,NaN,NaN,NaN,NaN,28559,...,150,16,340,239,320,15,454,357,451,27
Unnamed: 11,2006,942450,753836,8.26399e+06,1.24485e+06,NaN,NaN,NaN,NaN,30723,...,222,20,331,226,364,24,955,430,548,131
Unnamed: 12,2007,1.13169e+06,915653,9.5332e+06,1.47822e+06,NaN,NaN,NaN,NaN,34604,...,210,27,409,347,578,81,927,565,683,48
Unnamed: 13,2008,1.34282e+06,1.1147e+06,1.04758e+07,1.68418e+06,311,284,187,NaN,41542,...,444,33,341,285,635,72,598,285,731,58
Unnamed: 14,2009,1.17714e+06,998004,8.37971e+06,1.45399e+06,251,221,73,NaN,43113,...,254,38,384,324,437,87,882,403,765,22
Unnamed: 15,2010,1.35443e+06,1.11579e+06,9.98893e+06,1.69426e+06,197,156,76,NaN,48684,...,247,38,492,423,644,138,789,585,1061,22
Unnamed: 16,2011,1.64939e+06,1.35032e+06,1.15189e+07,1.98416e+06,196,147,53,NaN,57412,...,262,45,782,615,1089,232,1171,843,739,27
Unnamed: 17,2012,1.6551e+06,1.36978e+06,1.15029e+07,1.96034e+06,76,75,73,NaN,67991,...,262,46,1214,1029,1294,258,1298,1019,339,21
Unnamed: 18,2013,1.73153e+06,1.44534e+06,1.18591e+07,1.99726e+06,70,70,73,NaN,63495,...,180,39,1282,1080,1792,646,1252,1083,527,33
Unnamed: 19,2014,1.75258e+06,1.47996e+06,1.22872e+07,2.04874e+06,83,83,84,NaN,60376,...,544,41,850,704,1240,392,1213,1081,684,21
Unnamed: 20,2015,1.56156e+06,1.32976e+06,1.13307e+07,1.84436e+06,361,277,91,0,58399,...,190,15,701,613,767,186,1176,1085,348,22
Unnamed: 21,2016,1.57941e+06,1.35178e+06,1.11398e+07,1.8161e+06,437,339,39,NaN,59725,...,47,22,730,639,862,209,1135,1059,264,14
Unnamed: 22,2017,1.73493e+06,1.47423e+06,1.21164e+07,1.98463e+06,513,398,46,NaN,64366,...,62,22,649,585,1038,372,1050,981,432,14
Unnamed: 23,2018,1.8069e+06,1.5325e+06,1.31572e+07,2.23715e+06,576,447,52,NaN,NaN,...,82,14,635,551,1289,367,1170,1040,470,17